# Generated by Django 5.1.1 on 2024-09-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urldata',
            name='shorter',
        ),
        migrations.AddField(
            model_name='urldata',
            name='full_short_url',
            field=models.URLField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.URLField(),
        ),
    ]
